sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucket-name: xcalie-web-tlias
    region: cn-shenzhen
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxd7f756464fe96824
    secret: b77f94321713d6c5d8fa7a50fbc5a4b5